import { TeamMember, Project, Service } from './types';
import AchrafImage from "./assets/teams/Achraf.JPG";
import IslemImage from "./assets/teams/Islem.jpg";
import YoucefImage from "./assets/teams/Youcef.JPG";



import Studio from "./assets/projects/Studio_houari.png"
import CAC from "./assets/projects/CAC.png"
import MuscleUp from "./assets/projects/MuscleUp.png"
import Gamesooq from "./assets/projects/gamesooq2.png"
import Anonyto from "./assets/projects/Anonyto.png"
import portfolioWork12 from "./assets/projects/harfan.png";
import portfolioWork13 from "./assets/projects/syra.png"


export const teamMembers: TeamMember[] = [
  {
    id: "1",
    name: "Larbi Mohammed Achraf",
    nameAr: "العربي محمد أشرف" ,
    role: "Lead Full-Stack Engineer",
    roleAr: "مهندس تطوير متكامل رئيسي",
    bio: "Full-stack engineer with 3+ years of experience architecting scalable web platforms using React, Node.js, Python, and Django. Passionate about delivering high-performance digital solutions.",
    bioAr: "مهندس تطوير متكامل بخبرة تتجاوز 3 سنوات في بناء منصات ويب قابلة للتوسع باستخدام React و Node.js و Python و Django. شغوف بتقديم حلول رقمية عالية الأداء.",
    image: AchrafImage,
    github: "https://github.com/AchrafLarbi",
    linkedin: "https://www.linkedin.com/in/larbi-achraf-01902a283/",
    email: "larbiachraf03@gmail.com",
  },
  {
    id: "3",
    name: "Ouddane Youcef Fahd",
    nameAr: "ودان يوسف فهد",
    role: "Senior Mobile Engineer",
    roleAr: "مهندس تطبيقات جوال أول",
    bio: "Senior mobile engineer with 3+ years of experience building cross-platform applications with Flutter, Django, and Firebase. Focused on seamless user experiences and robust backend architecture.",
    bioAr: "مهندس تطبيقات جوال أول بخبرة تتجاوز 3 سنوات في بناء تطبيقات متعددة المنصات باستخدام Flutter و Django و Firebase. يركّز على تجربة مستخدم سلسة وبنية خلفية متينة.",
    image: YoucefImage,
    github: "https://github.com/yousef391",
    linkedin: "https://www.linkedin.com/in/ouddane-youcef-fahed-75842b283/",
    email: "yf.ouddan@esi-sba.dz",
  },
  {
    id: "4",
    name: "Ourred Islem Charaf Eddine",
    nameAr: "وراد اسلام شراف الدين",
    role: "UI/UX Designer & Frontend Engineer",
    roleAr: "مصمم تجربة المستخدم ومهندس واجهات",
    bio: "Creative designer and frontend engineer specializing in crafting intuitive, pixel-perfect interfaces. Transforms complex requirements into elegant, user-centered digital experiences.",
    bioAr: "مصمم مبدع ومهندس واجهات متخصص في صياغة واجهات بديهية ودقيقة. يحوّل المتطلبات المعقدة إلى تجارب رقمية أنيقة تركّز على المستخدم.",
    image: IslemImage,
    github: "https://github.com/Islemourred",
    linkedin: "https://www.linkedin.com/in/islem-ourred-02380327a/",
    email: "ic.ourred@esi-sba.dz",
  },

];

export const projects: Project[] = [
  {
    id: 1,
    title: "Gamesooq",
    titleAr: "حرفان",
    description:
      "We helped Harfan launch their brand with a complete visual identity and a comprehensive EdTech platform — combining Arabic language learning with Quran memorization, real-time progress analytics, and an intuitive management dashboard.",
    descriptionAr:
      "ساعدنا حرفان في إطلاق علامتهم التجارية بهوية بصرية متكاملة ومنصة تعليمية شاملة — تجمع بين تعلّم اللغة العربية وحفظ القرآن الكريم مع تحليلات تقدّم فورية ولوحة إدارة بديهية.",
    image: portfolioWork12,
    category: "Web",
    technologies: ["Django", "Python", "SQLite", "React"],
    github: "https://harfan-pi.vercel.app/",
    date: "2024",
    clientName: "Harfan Educational Institute",
    clientIndustry: "EdTech",
    clientIndustryAr: "التكنولوجيا التعليمية",
    clientStory: "An ambitious educational entrepreneur approached us with a vision to revolutionize Arabic language learning. They saw traditional learning methods falling short in engaging modern students and wanted to create a digital platform that would make learning Arabic and Quran memorization accessible, trackable, and effective for students of all ages.",
    clientStoryAr: "تواصل معنا رائد أعمال تعليمي طموح برؤية لإحداث ثورة في تعلّم اللغة العربية. لاحظ أن الأساليب التقليمية قاصرة عن جذب الطلاب المعاصرين، وأراد إنشاء منصة رقمية تجعل تعلّم العربية وحفظ القرآن متاحاً وقابلاً للتتبع وفعّالاً لطلاب من جميع الأعمار.",
    challenge: "The challenge was multifaceted: building a platform that respects the sanctity of Quran teaching while incorporating modern learning analytics, creating an interface simple enough for young students yet powerful enough for administrators, and ensuring the system could scale to accommodate thousands of students while tracking individual progress in real-time.",
    challengeAr: "كان التحدي متعدد الأوجه: بناء منصة تحترم قداسة تعليم القرآن مع دمج تحليلات التعلّم الحديثة، وإنشاء واجهة بسيطة للطلاب الصغار لكن قوية للإداريين، وضمان أن يتوسع النظام ليستوعب آلاف الطلاب مع تتبّع تقدم كل طالب في الوقت الفعلي.",
    solution: "We architected a full-stack EdTech platform with Django backend and React frontend, featuring a dual learning system for Arabic language and Quran memorization. We implemented real-time progress tracking with visual analytics, interactive lessons with multimedia support, and a comprehensive admin dashboard for teachers and institute management. The platform includes gamification elements to boost engagement and automated progress reports for parents.",
    solutionAr: "صممنا منصة تعليمية متكاملة مع خادم Django وواجهة React، تتميز بنظام تعلّم مزدوج للغة العربية وحفظ القرآن. نفذنا تتبعاً فورياً للتقدم مع تحليلات بصرية، ودروساً تفاعلية بدعم الوسائط المتعددة، ولوحة إدارة شاملة للمعلمين وإدارة المعهد. تتضمن المنصة عناصر التلعيب لتعزيز المشاركة وتقارير تقدم تلقائية للآباء.",
    results: [
      "Successfully launched with 500+ active students in the first 3 months",
      "Achieved 40% improvement in student engagement compared to traditional methods",
      "Reduced administrative workload by 60% through automated progress tracking",
      "Created a complete brand identity from scratch including logo, color scheme, and design system"
    ],
    resultsAr: [
      "إطلاق ناجح مع أكثر من 500 طالب نشط في الأشهر الثلاثة الأولى",
      "تحقيق تحسن بنسبة 40٪ في مشاركة الطلاب مقارنة بالأساليب التقليدية",
      "تقليل عبء العمل الإداري بنسبة 60٪ من خلال التتبع التلقائي للتقدم",
      "إنشاء هوية علامة تجارية كاملة من الصفر بما في ذلك الشعار ونظام الألوان والتصميم"
    ],
    timeline: "3 months",
    timelineAr: "3 أشهر",
  },

  {
    id: 8,
    title: "Maison SYRA",
    titleAr: "Maison SYRA",
    description:
      "A premium full-stack e-commerce experience for luxury artisan products — featuring secure authentication, seamless PayPal checkout, and a powerful admin management system.",
    descriptionAr:
      "تجربة تجارة إلكترونية متكاملة وفاخرة لمنتجات الحرفيين — مع مصادقة آمنة ودفع سلس عبر PayPal ونظام إدارة متقدم.",
    image: portfolioWork13,
    category: "Web",
    technologies: [
      "React",
      "Tailwind CSS",
      "Django",
      "Python",
      "Django REST Framework",
      "PayPal",
    ],
    github: "https://maisonsyra.vercel.app/",
    date: "2024",
    clientName: "Maison SYRA",
    clientIndustry: "Luxury E-commerce",
    clientIndustryAr: "التجارة الإلكترونية الفاخرة",
    clientStory: "A luxury artisan brand owner came to us frustrated with generic e-commerce platforms that couldn't capture the essence of their handcrafted products. They needed more than just an online store—they wanted a digital experience that would reflect the craftsmanship, exclusivity, and premium nature of their brand while reaching an international clientele.",
    clientStoryAr: "تواصل معنا مالك علامة تجارية فاخرة للحرف اليدوية، محبطاً من منصات التجارة الإلكترونية العامة التي لا تستطيع التقاط جوهر منتجاته المصنوعة يدوياً. احتاجوا أكثر من مجرد متجر إلكتروني—أرادوا تجربة رقمية تعكس الحرفية والحصرية والطابع الفاخر لعلامتهم التجارية مع الوصول إلى عملاء دوليين.",
    challenge: "Creating an e-commerce platform that balances luxury aesthetics with user-friendly functionality, implementing secure international payment processing, managing complex product variations and inventory, and building a robust admin panel that allows the client to maintain their brand's premium positioning while managing daily operations efficiently.",
    challengeAr: "إنشاء منصة تجارة إلكترونية توازن بين الجماليات الفاخرة والوظائف سهلة الاستخدام، وتطبيق معالجة دفع دولية آمنة، وإدارة تنويعات المنتجات والمخزون المعقدة، وبناء لوحة إدارة قوية تسمح للعميل بالحفاظ على الموقع الفاخر لعلامته التجارية مع إدارة العمليات اليومية بكفاءة.",
    solution: "We built a sophisticated e-commerce platform using React for a fluid, elegant frontend and Django REST Framework for a powerful backend. The platform features a luxury-focused design with high-quality product galleries, seamless PayPal integration for secure international transactions, advanced product filtering and search, real-time inventory management, and a comprehensive admin dashboard for order processing, customer management, and analytics.",
    solutionAr: "بنينا منصة تجارة إلكترونية متطورة باستخدام React لواجهة أمامية سلسة وأنيقة و Django REST Framework لخادم قوي. تتميز المنصة بتصميم يركز على الفخامة مع معارض منتجات عالية الجودة، وتكامل سلس مع PayPal للمعاملات الدولية الآمنة، وتصفية وبحث متقدمان للمنتجات، وإدارة المخزون في الوقت الفعلي، ولوحة إدارة شاملة لمعالجة الطلبات وإدارة العملاء والتحليلات.",
    results: [
      "Achieved 85% increase in online sales within the first 6 months",
      "Expanded customer base to 12 international markets",
      "Reduced cart abandonment rate by 45% with optimized checkout flow",
      "Successfully processed 1000+ secure international transactions",
      "Improved brand perception with premium digital presence"
    ],
    resultsAr: [
      "تحقيق زيادة بنسبة 85٪ في المبيعات عبر الإنترنت خلال الأشهر الستة الأولى",
      "توسيع قاعدة العملاء إلى 12 سوقاً دولياً",
      "تقليل معدل التخلي عن عربة التسوق بنسبة 45٪ مع تدفق دفع محسّن",
      "معالجة أكثر من 1000 معاملة دولية آمنة بنجاح",
      "تحسين تصور العلامة التجارية مع تواجد رقمي راقٍ"
    ],
    timeline: "4 months",
    timelineAr: "4 أشهر",
  },


  {
    id: 1,
    title: "Gamesooq",
    titleAr: "Gamesooq",
    description: "We helped Gamesooq launch their brand with a complete visual identity and Algeria's premier gaming marketplace — a scalable platform enabling gamers to buy, sell, and trade video games and consoles with built-in security and real-time notifications.",
    descriptionAr: "ساعدنا Gamesooq في إطلاق علامتهم التجارية بهوية بصرية متكاملة وسوق الألعاب الرائد في الجزائر — منصة قابلة للتوسع تمكّن اللاعبين من شراء وبيع وتبادل ألعاب الفيديو وأجهزة التحكم بأمان مدمج وإشعارات فورية.",
    image: Gamesooq,
    category: "Mobile",
    technologies: ["Flutter", "Dart", "Firebase", "Javascript", "NodeJs"],
    date: "2025",
    github: "https://www.gamesooq.com/",
    clientName: "Gamesooq Founders",
    clientIndustry: "Gaming Marketplace",
    clientIndustryAr: "سوق الألعاب",
    clientStory: "A group of passionate gamers approached us with a problem they experienced firsthand: buying and selling video games in Algeria was a fragmented, unreliable process scattered across social media and untrustworthy platforms. They envisioned creating Algeria's first dedicated, secure marketplace for gamers, but needed a complete brand identity and a mobile-first platform that could compete with international standards.",
    clientStoryAr: "تواصلت معنا مجموعة من اللاعبين المتحمسين بمشكلة واجهوها شخصياً: كان شراء وبيع ألعاب الفيديو في الجزائر عملية مجزأة وغير موثوقة منتشرة عبر وسائل التواصل الاجتماعي ومنصات غير موثوقة. تصوّروا إنشاء أول سوق مخصص وآمن للاعبين في الجزائر، لكنهم احتاجوا هوية علامة تجارية كاملة ومنصة تركز على الجوال يمكنها منافسة المعايير الدولية.",
    challenge: "Building trust in a market where scams were common, creating a cross-platform mobile app that works seamlessly on both iOS and Android, implementing secure payment and user verification systems, designing an intuitive interface for diverse age groups, and establishing a brand identity that would resonate with Algeria's gaming community while standing out in the marketplace.",
    challengeAr: "بناء الثقة في سوق كانت فيه عمليات الاحتيال شائعة، وإنشاء تطبيق جوال متعدد المنصات يعمل بسلاسة على كل من iOS و Android، وتطبيق أنظمة دفع وتحقق من المستخدم آمنة، وتصميم واجهة بديهية لفئات عمرية متنوعة، وإنشاء هوية علامة تجارية تتردد صداها مع مجتمع الألعاب الجزائري مع التميز في السوق.",
    solution: "We developed a full-featured mobile marketplace using Flutter for cross-platform compatibility, Firebase for real-time functionality and secure authentication, and Node.js for backend operations. The platform includes user verification systems, secure in-app messaging, real-time push notifications for offers and messages, advanced search and filtering, user ratings and reviews, and escrow-like transaction protection. We also created a complete brand identity including logo design, visual system, and marketing materials.",
    solutionAr: "طورنا سوقاً جوالاً كامل الميزات باستخدام Flutter للتوافق متعدد المنصات، و Firebase للوظائف في الوقت الفعلي والمصادقة الآمنة، و Node.js لعمليات الخادم. تتضمن المنصة أنظمة التحقق من المستخدمين، ومراسلة آمنة داخل التطبيق، وإشعارات فورية للعروض والرسائل، وبحث وتصفية متقدمان، وتقييمات ومراجعات المستخدمين، وحماية المعاملات الشبيهة بالضمان. أنشأنا أيضاً هوية علامة تجارية كاملة بما في ذلك تصميم الشعار والنظام البصري والمواد التسويقية.",
    results: [
      "Launched successfully with 2000+ registered users in the first month",
      "Facilitated over 5000 secure gaming transactions",
      "Achieved 4.8/5 star rating on app stores",
      "Became Algeria's leading gaming marketplace platform",
      "Built a trusted community with <2% dispute rate",
      "Created complete brand identity from concept to launch"
    ],
    resultsAr: [
      "إطلاق ناجح مع أكثر من 2000 مستخدم مسجل في الشهر الأول",
      "تسهيل أكثر من 5000 معاملة ألعاب آمنة",
      "تحقيق تقييم 4.8/5 نجوم في متاجر التطبيقات",
      "أصبحت منصة سوق الألعاب الرائدة في الجزائر",
      "بناء مجتمع موثوق مع معدل نزاع أقل من 2٪",
      "إنشاء هوية علامة تجارية كاملة من المفهوم إلى الإطلاق"
    ],
    timeline: "5 months",
    timelineAr: "5 أشهر",
  },
  {
    id: 2,
    title: "Studio Houari ",
    titleAr: "ستوديو هواري ",
    description: "A visually stunning portfolio platform for a professional photography studio — designed to showcase creative work and convert visitors into clients.",
    descriptionAr: "منصة عرض بصرية مذهلة لاستوديو تصوير احترافي — مصمّمة لإبراز الأعمال الإبداعية وتحويل الزوار إلى عملاء.",
    image: Studio,
    category: "Web",
    technologies: ["React", "Tailwind css", "Javascript", "Supabase"],
    date: "2024",
    github: "https://studiohouari.netlify.app/",
    clientName: "Studio Houari",
    clientIndustry: "Professional Photography",
    clientIndustryAr: "التصوير الاحترافي",
    clientStory: "A talented professional photographer approached us with a common frustration: their Instagram page wasn't converting followers into paying clients. They needed a professional digital presence that would showcase their event photography, portraits, and commercial work in a way that reflected their artistic vision and made it easy for potential clients to book their services.",
    clientStoryAr: "تواصل معنا مصور فوتوغرافي موهوب محترف بإحباط شائع: لم تكن صفحته على إنستغرام تحوّل المتابعين إلى عملاء يدفعون. احتاج إلى تواجد رقمي احترافي يعرض تصوير الفعاليات والصور الشخصية والأعمال التجارية بطريقة تعكس رؤيته الفنية وتسهّل على العملاء المحتملين حجز خدماته.",
    challenge: "Creating a portfolio that balances artistic presentation with business functionality, ensuring stunning visual performance without sacrificing load times, implementing an intuitive booking inquiry system, organizing diverse photography categories (weddings, events, portraits, commercial), and building a content management system that allows the photographer to update their portfolio independently.",
    challengeAr: "إنشاء محفظة توازن بين العرض الفني والوظائف التجارية، وضمان أداء بصري مذهل دون التضحية بأوقات التحميل، وتطبيق نظام استفسار حجز بديهي، وتنظيم فئات التصوير المتنوعة (الأعراس والفعاليات والصور الشخصية والتجارية)، وبناء نظام إدارة محتوى يسمح للمصور بتحديث محفظته بشكل مستقل.",
    solution: "We developed a high-performance portfolio website using React for dynamic interactions and smooth animations, Tailwind CSS for a sleek, modern design system, and Supabase for backend functionality including contact forms and image management. The platform features lazy-loading optimized galleries, category-based portfolio organization, an integrated contact and booking system, responsive design optimized for all devices, and an easy-to-use admin panel for portfolio updates.",
    solutionAr: "طورنا موقع محفظة عالي الأداء باستخدام React للتفاعلات الديناميكية والرسوم المتحركة السلسة، و Tailwind CSS لنظام تصميم أنيق وحديث، و Supabase لوظائف الخادم بما في ذلك نماذج الاتصال وإدارة الصور. تتميز المنصة بمعارض محسّنة للتحميل التدريجي، وتنظيم المحفظة على أساس الفئات، ونظام اتصال وحجز متكامل، وتصميم متجاوب محسّن لجميع الأجهزة، ولوحة إدارة سهلة الاستخدام لتحديثات المحفظة.",
    results: [
      "Increased client inquiries by 150% within the first 3 months",
      "Achieved average page load time of under 2 seconds with high-resolution images",
      "Converted 35% of website visitors into booking inquiries",
      "Successfully showcased 200+ professional photography projects",
      "Established professional online brand presence independent of social media"
    ],
    resultsAr: [
      "زيادة استفسارات العملاء بنسبة 150٪ خلال الأشهر الثلاثة الأولى",
      "تحقيق متوسط وقت تحميل الصفحة أقل من ثانيتين مع صور عالية الدقة",
      "تحويل 35٪ من زوار الموقع إلى استفسارات حجز",
      "عرض أكثر من 200 مشروع تصوير احترافي بنجاح",
      "إنشاء تواجد علامة تجارية احترافية عبر الإنترنت مستقلة عن وسائل التواصل الاجتماعي"
    ],
    timeline: "2 months",
    timelineAr: "شهران",
  },
  {
    id: 3,
    title: "Anonyto ",
    titleAr: "Anonyto ",
    description: "An intelligent privacy-first platform that automatically detects and anonymizes sensitive data before transmission — ensuring compliance and protecting user information at scale.",
    descriptionAr: "منصة ذكية تعتمد الخصوصية أولاً، تكتشف وتخفي البيانات الحساسة تلقائياً قبل الإرسال — لضمان الامتثال وحماية معلومات المستخدمين على نطاق واسع.",
    image: Anonyto ,
    category: "Web",
    technologies: ["React", "Tailwind css", "Django","Python", "SQLite", "RESTful APIs"],
    github: "http://anonyto.com/",
    date: "2026",
    clientName: "Tech Compliance Startup",
    clientIndustry: "Data Privacy & Security",
    clientIndustryAr: "خصوصية البيانات والأمن",
    clientStory: "A data compliance officer from a growing tech startup contacted us with a critical problem: their team was accidentally exposing sensitive customer data (emails, phone numbers, addresses) in support tickets, analytics tools, and shared documents. They needed an intelligent solution that could automatically detect and anonymize personal information before it entered their systems, ensuring GDPR compliance and protecting customer privacy without disrupting their workflow.",
    clientStoryAr: "اتصل بنا مسؤول امتثال البيانات من شركة تقنية ناشئة متنامية مع مشكلة حرجة: كان فريقهم يكشف عن طريق الخطأ بيانات العملاء الحساسة (البريد الإلكتروني وأرقام الهواتف والعناوين) في تذاكر الدعم وأدوات التحليلات والمستندات المشتركة. احتاجوا إلى حل ذكي يمكنه اكتشاف وإخفاء المعلومات الشخصية تلقائياً قبل دخولها إلى أنظمتهم، لضمان الامتثال ل GDPR وحماية خصوصية العملاء دون تعطيل سير عملهم.",
    challenge: "Building an AI-powered system capable of detecting various types of sensitive data (PII) across different formats and languages, ensuring real-time processing without latency, maintaining high accuracy to avoid false positives/negatives, creating a seamless API integration for existing workflows, and building a user-friendly interface that requires minimal technical knowledge to operate.",
    challengeAr: "بناء نظام يعمل بالذكاء الاصطناعي قادر على اكتشاف أنواع مختلفة من البيانات الحساسة (PII) عبر تنسيقات ولغات مختلفة، وضمان المعالجة في الوقت الفعلي دون تأخير، والحفاظ على دقة عالية لتجنب الإيجابيات/السلبيات الكاذبة، وإنشاء تكامل API سلس لسير العمل الحالي، وبناء واجهة سهلة الاستخدام تتطلب الحد الأدنى من المعرفة التقنية للتشغيل.",
    solution: "We architected an intelligent privacy platform using Django and Python for robust backend processing with machine learning models, React for an intuitive frontend interface, and RESTful APIs for seamless integration. The system uses advanced NLP and regex patterns to detect sensitive information, provides real-time anonymization with customizable rules, includes a testing playground for validation, offers detailed analytics on detected and anonymized data, and features comprehensive API documentation for developer integration.",
    solutionAr: "صممنا منصة خصوصية ذكية باستخدام Django و Python لمعالجة خلفية قوية مع نماذج التعلم الآلي، و React لواجهة أمامية بديهية، و RESTful APIs للتكامل السلس. يستخدم النظام معالجة اللغة الطبيعية المتقدمة وأنماط regex لاكتشاف المعلومات الحساسة، ويوفر إخفاء الهوية في الوقت الفعلي مع قواعد قابلة للتخصيص، ويتضمن ملعباً للاختبار للتحقق، ويقدم تحليلات مفصلة عن البيانات المكتشفة والمخفية، ويتميز بوثائق API شاملة لتكامل المطورين.",
    results: [
      "Helped client achieve 100% GDPR compliance for data handling",
      "Automatically detected and anonymized 50,000+ instances of sensitive data per month",
      "Achieved 98.5% accuracy in PII detection",
      "Reduced data breach risk by implementing automated protection",
      "Integrated seamlessly with existing tools with zero downtime",
      "Processing time under 100ms per request maintaining real-time performance"
    ],
    resultsAr: [
      "ساعدنا العميل على تحقيق الامتثال الكامل ل GDPR لمعالجة البيانات",
      "اكتشاف وإخفاء الهوية تلقائياً لأكثر من 50،000 حالة من البيانات الحساسة شهرياً",
      "تحقيق دقة 98.5٪ في اكتشاف PII",
      "تقليل مخاطر اختراق البيانات من خلال تطبيق الحماية التلقائية",
      "التكامل السلس مع الأدوات الحالية بدون وقت توقف",
      "وقت المعالجة أقل من 100 مللي ثانية لكل طلب مع الحفاظ على الأداء في الوقت الفعلي"
    ],
    timeline: "4 months",
    timelineAr: "4 أشهر",
  },
  {
    id: 4,
    title: "MuscleUp",
    titleAr: "MuscleUp",
    description:
      "A customized e-commerce platform for the fitness industry — built around the client's brand identity and product catalog, featuring personalized workout plans, smart dietary recommendations, and comprehensive progress analytics.",
    descriptionAr: "منصة تجارة إلكترونية مخصصة لقطاع اللياقة البدنية — مبنية حول هوية العميل التجارية وكتالوج منتجاته، مع خطط تمارين مخصصة وتوصيات غذائية ذكية وتحليلات تقدم شاملة.",
    image: MuscleUp,
    category: "Mobile",
    technologies: ["React", "Tailwind css", "Django","Python", "SQLite", "RESTful APIs"],
    date: "2025",
    github: "https://gym-website-7avc.vercel.app/?store=youcefnut/",
    clientName: "MuscleUp Fitness",
    clientIndustry: "Fitness & Wellness",
    clientIndustryAr: "اللياقة البدنية والصحة",
    clientStory: "A fitness entrepreneur and personal trainer came to us with an ambitious vision: they wanted to transition from in-person training to a scalable digital platform that could sell fitness supplements while also providing personalized workout plans and nutrition guidance to their growing community. They needed more than just an e-commerce store—they wanted a complete fitness ecosystem.",
    clientStoryAr: "تواصل معنا رائد أعمال في اللياقة البدنية ومدرب شخصي برؤية طموحة: أرادوا الانتقال من التدريب الشخصي إلى منصة رقمية قابلة للتوسع يمكنها بيع مكملات اللياقة البدنية مع توفير خطط تمارين مخصصة وإرشادات غذائية لمجتمعهم المتنامي. احتاجوا أكثر من مجرد متجر للتجارة الإلكترونية—أرادوا نظاماً بيئياً كاملاً للياقة البدنية.",
    challenge: "Creating a platform that seamlessly combines e-commerce functionality with fitness coaching features, developing personalized workout recommendation algorithms based on user goals and fitness levels, integrating nutrition tracking and smart dietary suggestions, building progress analytics that motivate users, managing inventory for supplements while handling digital content delivery, and ensuring mobile-first design for users who access the platform at the gym.",
    challengeAr: "إنشاء منصة تجمع بسلاسة بين وظائف التجارة الإلكترونية وميزات التدريب على اللياقة البدنية، وتطوير خوارزميات توصيات التمارين المخصصة بناءً على أهداف المستخدمين ومستويات اللياقة، ودمج تتبع التغذية واقتراحات الحمية الذكية، وبناء تحليلات التقدم التي تحفز المستخدمين، وإدارة المخزون للمكملات مع معالجة تسليم المحتوى الرقمي، وضمان تصميم أولاً على الجوال للمستخدمين الذين يدخلون إلى المنصة في صالة الألعاب الرياضية.",
    solution: "We built a comprehensive fitness platform using React for a dynamic, responsive frontend, Django and Python for powerful backend logic including workout algorithms, and SQLite for efficient data management. The platform features a full e-commerce system for supplement sales, personalized workout plan generator based on user profiles, smart nutrition tracking and meal recommendations, progress dashboard with charts and achievements, video exercise library with demonstrations, user community features for motivation, and mobile-optimized interface for gym use.",
    solutionAr: "بنينا منصة لياقة بدنية شاملة باستخدام React لواجهة أمامية ديناميكية ومتجاوبة، و Django و Python لمنطق خلفي قوي بما في ذلك خوارزميات التمارين، و SQLite لإدارة البيانات بكفاءة. تتميز المنصة بنظام تجارة إلكترونية كامل لمبيعات المكملات، ومولد خطط تمارين مخصصة بناءً على ملفات تعريف المستخدمين، وتتبع التغذية الذكي وتوصيات الوجبات، ولوحة تقدم مع رسوم بيانية وإنجازات، ومكتبة فيديو للتمارين مع عروض توضيحية، وميزات مجتمع المستخدمين للتحفيز، وواجهة محسّنة للجوال لاستخدام الصالة الرياضية.",
    results: [
      "Grew user base to 3000+ active members within 6 months",
      "Achieved $50K+ monthly revenue from supplement sales",
      "Generated 5000+ personalized workout plans",
      "Maintained 75% user retention rate for premium features",
      "Reduced client support time by 50% with automated recommendations",
      "Users reported average 25% improvement in fitness goals achievement"
    ],
    resultsAr: [
      "نمت قاعدة المستخدمين إلى أكثر من 3000 عضو نشط خلال 6 أشهر",
      "تحقيق إيرادات شهرية تزيد عن 50 ألف دولار من مبيعات المكملات",
      "إنشاء أكثر من 5000 خطة تمارين مخصصة",
      "الحفاظ على معدل احتفاظ 75٪ للمستخدمين للميزات المميزة",
      "تقليل وقت دعم العملاء بنسبة 50٪ مع التوصيات التلقائية",
      "أبلغ المستخدمون عن تحسن بمتوسط 25٪ في تحقيق أهداف اللياقة البدنية"
    ],
    timeline: "3 months",
    timelineAr: "3 أشهر",
  },
  {
    id: 6,
    title: "CAC de Batna",
    titleAr: "CAC de Batna",
    description: "A comprehensive UI/UX design system for Algeria's Centre Anti-Cancer de Batna — crafting patient-centered digital interfaces that streamline diagnosis workflows and enhance the care experience.",
    descriptionAr: "نظام تصميم واجهات شامل لمركز مكافحة السرطان في باتنة — تصميم واجهات رقمية تتمحور حول المريض لتسهيل سير عمل التشخيص وتحسين تجربة الرعاية.",
    image: CAC,
    category: "UI/UX",
    technologies: ["Figma", "Sketch", "Adobe XD","Canva"],
    github: "https://www.figma.com/design/sCKL4k5BH6ggLQ0LXWkuOJ/Blog-anti-cancer?node-id=3-510&t=KWFOafgkQfEogpQm-0",
    date: "2024",
    clientName: "Centre Anti-Cancer de Batna",
    clientIndustry: "Healthcare - Oncology",
    clientIndustryAr: "الرعاية الصحية - علم الأورام",
    clientStory: "The administration of Algeria's Centre Anti-Cancer de Batna approached us with a sensitive mission: their existing patient management system was outdated, causing confusion for both staff and patients during an already stressful time. They needed a complete UI/UX redesign that would make complex medical workflows intuitive, reduce patient anxiety through clear communication, and help their staff focus on care rather than navigating complicated interfaces.",
    clientStoryAr: "تواصلت معنا إدارة مركز مكافحة السرطان في باتنة بمهمة حساسة: كان نظام إدارة المرضى الحالي قديماً، مما يسبب الارتباك لكل من الموظفين والمرضى خلال وقت مجهد بالفعل. احتاجوا إلى إعادة تصميم كاملة لواجهة المستخدم/تجربة المستخدم من شأنها أن تجعل سير العمل الطبي المعقد بديهياً، وتقلل من قلق المريض من خلال التواصل الواضح، وتساعد موظفيهم على التركيز على الرعاية بدلاً من التنقل في واجهات معقدة.",
    challenge: "Designing for a sensitive healthcare context where clarity is critical, accommodating diverse user groups (patients, doctors, nurses, administrators) with different needs, simplifying complex medical workflows without losing essential information, ensuring accessibility for elderly patients and those with limited digital literacy, creating a calming, reassuring visual language appropriate for cancer care, and delivering designs that could be implemented within the center's technical constraints.",
    challengeAr: "التصميم لسياق رعاية صحية حساس حيث الوضوح حرج، واستيعاب مجموعات مستخدمين متنوعة (المرضى والأطباء والممرضات والإداريين) بحاجات مختلفة، وتبسيط سير العمل الطبي المعقد دون فقدان المعلومات الأساسية، وضمان إمكانية الوصول للمرضى المسنين وذوي معرفة رقمية محدودة، وإنشاء لغة بصرية مهدئة ومطمئنة مناسبة لرعاية السرطان، وتسليم تصاميم يمكن تنفيذها ضمن القيود التقنية للمركز.",
    solution: "We conducted extensive user research including interviews with patients, doctors, and staff to understand pain points. Using Figma as our primary tool, we created a comprehensive design system including patient registration and appointment workflows, diagnosis tracking interfaces, treatment scheduling systems, medical records access, staff dashboards for workflow management, and a patient education section. We developed a calming color palette, clear typography for medical information, intuitive navigation patterns, and accessibility features for diverse users.",
    solutionAr: "أجرينا أبحاث مستخدمين واسعة بما في ذلك مقابلات مع المرضى والأطباء والموظفين لفهم نقاط الألم. باستخدام Figma كأداتنا الأساسية، أنشأنا نظام تصميم شامل بما في ذلك سير عمل تسجيل المرضى والمواعيد، وواجهات تتبع التشخيص، وأنظمة جدولة العلاج، والوصول إلى السجلات الطبية، ولوحات معلومات الموظفين لإدارة سير العمل، وقسم تثقيف المرضى. طورنا لوحة ألوان مهدئة، وطباعة واضحة للمعلومات الطبية، وأنماط تنقل بديهية، وميزات إمكانية الوصول للمستخدمين المتنوعين.",
    results: [
      "Reduced patient registration time by 40% with streamlined workflows",
      "Improved staff satisfaction with 90% reporting easier system navigation",
      "Created complete design system with 50+ components and 100+ screens",
      "Reduced patient confusion with clear visual hierarchies and instructions",
      "Designed accessible interfaces meeting WCAG 2.1 AA standards",
      "Delivered comprehensive Figma documentation for development team"
    ],
    resultsAr: [
      "تقليل وقت تسجيل المرضى بنسبة 40٪ مع سير عمل مبسط",
      "تحسين رضا الموظفين مع 90٪ يبلغون عن تنقل أسهل في النظام",
      "إنشاء نظام تصميم كامل مع أكثر من 50 مكوناً وأكثر من 100 شاشة",
      "تقليل ارتباك المرضى مع تسلسلات هرمية بصرية وتعليمات واضحة",
      "تصميم واجهات يمكن الوصول إليها تلبي معايير WCAG 2.1 AA",
      "تسليم وثائق Figma شاملة لفريق التطوير"
    ],
    timeline: "2.5 months",
    timelineAr: "شهران ونصف",
  },
];

export const services: Service[] = [
  {
    id: "1",
    icon: "Code2",
    title: "Web Development",
    titleAr: "تطوير مواقع الويب",
    description: "We architect and build scalable, high-performance web platforms tailored to your business — from landing pages to complex enterprise applications.",
    descriptionAr: "نصمم ونبني منصات ويب قابلة للتوسع وعالية الأداء مصممة خصيصاً لعملك — من صفحات الهبوط إلى التطبيقات المؤسسية المعقدة.",
    features: ["Responsive Design", "SEO Optimization", "Performance Tuning", "API Integration"],
    featuresAr: ["تصميم متجاوب", "تحسين محركات البحث", "ضبط الأداء", "تكامل API"],
    color: "blue",
  },
  {
    id: "2",
    icon: "Smartphone",
    title: "Mobile Development",
    titleAr: "تطوير تطبيقات الجوال",
    description: "We craft native and cross-platform mobile experiences for iOS and Android — built for speed, reliability, and seamless user engagement.",
    descriptionAr: "نصنع تجارب جوال أصلية ومتعددة المنصات لنظامي iOS و Android — مصممة للسرعة والموثوقية والتفاعل السلس مع المستخدم.",
    features: ["Native Apps", "Cross-Platform", "Push Notifications", "Offline Support"],
    featuresAr: ["تطبيقات أصلية", "متعدد المنصات", "إشعارات فورية", "دعم وضع عدم الاتصال"],
    color: "green",
  },
  {
    id: "3",
    icon: "Globe",
    title: "Digital Presence",
    titleAr: "التواجد الرقمي",
    description: "We establish and amplify your online presence through strategic digital infrastructure — from domain architecture to analytics-driven growth.",
    descriptionAr: "نؤسس ونعزز تواجدك الرقمي من خلال بنية رقمية استراتيجية — من هندسة النطاقات إلى النمو القائم على التحليلات.",
    features: ["Domain Setup", "Hosting Solutions", "Email Services", "Analytics"],
    featuresAr: ["إعداد النطاق", "حلول الاستضافة", "خدمات البريد الإلكتروني", "التحليلات"],
    color: "purple",
  },
  {
    id: "4",
    icon: "Palette",
    title: "UI/UX Design",
    titleAr: "تصميم واجهات المستخدم",
    description: "We design intuitive, visually exceptional interfaces grounded in user research — every pixel serves a purpose, every interaction tells a story.",
    descriptionAr: "نصمم واجهات بديهية واستثنائية بصرياً مبنية على أبحاث المستخدم — كل بكسل له هدف وكل تفاعل يروي قصة.",
    features: ["User Research", "Wireframing", "Prototyping", "Usability Testing"],
    featuresAr: ["أبحاث المستخدم", "التخطيط الهيكلي", "النماذج الأولية", "اختبار قابلية الاستخدام"],
    color: "pink",
  },
  {
    id: "5",
    icon: "Brain",
    title: "AI Solutions",
    titleAr: "حلول الذكاء الاصطناعي",
    description: "We integrate intelligent AI systems that transform your operations — from predictive analytics and NLP to computer vision and custom ML models.",
    descriptionAr: "ندمج أنظمة ذكاء اصطناعي متقدمة تحوّل عملياتك — من التحليلات التنبؤية ومعالجة اللغة الطبيعية إلى الرؤية الحاسوبية ونماذج التعلم الآلي المخصصة.",
    features: ["Machine Learning", "Natural Language Processing", "Predictive Analytics", "Computer Vision"],
    featuresAr: ["التعلم الآلي", "معالجة اللغة الطبيعية", "التحليلات التنبؤية", "رؤية الكمبيوتر"],
    color: "indigo",
  },
  {
    id: "6",
    icon: "Zap",
    title: "AI Automation",
    titleAr: "أتمتة الذكاء الاصطناعي",
    description: "We engineer AI-driven automation that eliminates bottlenecks — intelligent chatbots, document processing, and end-to-end business workflow optimization.",
    descriptionAr: "نهندس أتمتة مدفوعة بالذكاء الاصطناعي تزيل العوائق — روبوتات محادثة ذكية ومعالجة مستندات وتحسين شامل لسير العمل التجاري.",
    features: ["Workflow Automation", "Chatbots & Virtual Assistants", "Document Processing", "Business Process Automation"],
    featuresAr: ["أتمتة سير العمل", "روبوتات الدردشة والمساعدين الافتراضيين", "معالجة المستندات", "أتمتة العمليات التجارية"],
    color: "orange",
  },
];