import { TeamMember, Project, Service } from './types';


export const teamMembers: TeamMember[] = [
  {
    id: 1,
    name: "John Smith",
    nameAr: "جون سميث",
    role: "Full Stack Developer",
    roleAr: "مطور الويب المتكامل",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop"
  },
  {
    id: 2,
    name: "Sarah Johnson",
    nameAr: "سارة جونسون",
    role: "UI/UX Designer",
    roleAr: "مصمم واجهات المستخدم",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop"
  },
  {
    id: 3,
    name: "Ahmed Hassan",
    nameAr: "أحمد حسن",
    role: "Mobile Developer",
    roleAr: "مطور تطبيقات الموبايل",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop"
  },
  {
    id: 4,
    name: "Lina Khalil",
    nameAr: "لينا خليل",
    role: "Project Manager",
    roleAr: "مدير المشاريع",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop"
  }
];

export const projects: Project[] = [
  {
    id: 1,
    title: "E-commerce Platform",
    titleAr: "منصة التجارة الإلكترونية",
    description: "A full-featured e-commerce platform with product management, cart, and payment integration.",
    descriptionAr: "منصة تجارة إلكترونية متكاملة مع إدارة المنتجات، سلة التسوق، ودمج المدفوعات.",
    image: "/placeholder.svg?height=600&width=800",
    category: "Web",
    technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    link: "#",
    github: "https://github.com",
    date: "2023",
  },
  {
    id: 2,
    title: "Health & Fitness App",
    titleAr: "تطبيق الصحة واللياقة",
    description:
      "Mobile application for tracking workouts, nutrition, and health metrics with personalized recommendations.",
    descriptionAr: "تطبيق جوال لتتبع التمارين والتغذية ومقاييس الصحة مع توصيات مخصصة.",
    image: "/placeholder.svg?height=600&width=800",
    category: "Mobile",
    technologies: ["React Native", "Firebase", "Redux", "HealthKit"],
    link: "#",
    date: "2023",
    github: "https://github.com",
  },
  {
    id: 3,
    title: "Corporate Identity",
    titleAr: "هوية الشركة",
    description: "Complete branding package including logo design, color palette, typography, and brand guidelines.",
    descriptionAr: "حزمة علامة تجارية كاملة تشمل تصميم الشعار، لوحة الألوان، الطباعة، وإرشادات العلامة التجارية.",
    image: "/placeholder.svg?height=600&width=800",
    category: "Branding",
    technologies: ["Illustrator", "Photoshop", "InDesign"],
    link: "#",
    date: "2022",
    github: "https://github.com",
  },
  {
    id: 4,
    title: "Real Estate Portal",
    titleAr: "بوابة العقارات",
    description: "Property listing platform with advanced search, virtual tours, and agent management system.",
    descriptionAr: "منصة قوائم العقارات مع بحث متقدم، جولات افتراضية، ونظام إدارة الوكلاء.",
    image: "/placeholder.svg?height=600&width=800",
    category: "Web",
    technologies: ["Next.js", "Prisma", "PostgreSQL", "Google Maps API"],
    link: "#",
    github: "https://github.com",
    date: "2023",
  },
  {
    id: 5,
    title: "Financial Dashboard",
    titleAr: "لوحة التحكم المالية",
    description: "Interactive dashboard for financial analytics with real-time data visualization and reporting.",
    descriptionAr: "لوحة تحكم تفاعلية للتحليلات المالية مع تصور البيانات في الوقت الفعلي وإعداد التقارير.",
    image: "/placeholder.svg?height=600&width=800",
    category: "UI/UX",
    technologies: ["Figma", "Adobe XD", "Sketch"],
    link: "#",
    date: "2022",
    github: "https://github.com",
  },
  {
    id: 6,
    title: "Delivery Tracking App",
    titleAr: "تطبيق تتبع التوصيل",
    description: "Mobile application for real-time package tracking with driver management and customer notifications.",
    descriptionAr: "تطبيق جوال لتتبع الطرود في الوقت الفعلي مع إدارة السائقين وإشعارات العملاء.",
    image: "/placeholder.svg?height=600&width=800",
    category: "Mobile",
    technologies: ["Flutter", "Firebase", "Google Maps", "Push Notifications"],
    link: "#",
    github: "https://github.com",
    date: "2022",
  },
  {
    id: 7,
    title: "Educational Platform",
    titleAr: "منصة تعليمية",
    description: "Online learning platform with course management, video streaming, and interactive assessments.",
    descriptionAr: "منصة تعلم عبر الإنترنت مع إدارة الدورات، بث الفيديو، والتقييمات التفاعلية.",
    image: "/placeholder.svg?height=600&width=800",
    category: "Web",
    technologies: ["Vue.js", "Laravel", "MySQL", "WebRTC"],
    link: "#",
    date: "2021",
    github: "https://github.com",
  },
  {
    id: 8,
    title: "Restaurant Management",
    titleAr: "إدارة المطاعم",
    description:
      "Comprehensive system for restaurant operations including ordering, kitchen management, and analytics.",
    descriptionAr: "نظام شامل لعمليات المطاعم بما في ذلك الطلبات، إدارة المطبخ، والتحليلات.",
    image: "/placeholder.svg?height=600&width=800",
    category: "Web",
    technologies: ["React", "Express", "Socket.io", "PostgreSQL"],
    link: "#",
    github: "https://github.com",
    date: "2021",
  },
];

export const services: Service[] = [
  {
    id: "1",
    icon: "Code2",
    title: "Web Development",
    titleAr: "تطوير الويب",
    description: "Custom websites and web applications built with the latest technologies.",
    descriptionAr: "مواقع ويب وتطبيقات ويب مخصصة مبنية بأحدث التقنيات.",
    features: ["Responsive Design", "SEO Optimization", "Performance Tuning", "API Integration"],
    featuresAr: ["تصميم متجاوب", "تحسين محركات البحث", "ضبط الأداء", "تكامل API"],
    color: "blue",
  },
  {
    id: "2",
    icon: "Smartphone",
    title: "Mobile Development",
    titleAr: "تطوير تطبيقات الجوال",
    description: "Native and cross-platform mobile applications for iOS and Android.",
    descriptionAr: "تطبيقات جوال أصلية ومتعددة المنصات لنظامي iOS و Android.",
    features: ["Native Apps", "Cross-Platform", "Push Notifications", "Offline Support"],
    featuresAr: ["تطبيقات أصلية", "متعدد المنصات", "إشعارات فورية", "دعم وضع عدم الاتصال"],
    color: "green",
  },
  {
    id: "3",
    icon: "Globe",
    title: "Digital Presence",
    titleAr: "التواجد الرقمي",
    description: "Establish and grow your online presence with comprehensive digital solutions.",
    descriptionAr: "تأسيس وتنمية تواجدك عبر الإنترنت مع حلول رقمية شاملة.",
    features: ["Domain Setup", "Hosting Solutions", "Email Services", "Analytics"],
    featuresAr: ["إعداد النطاق", "حلول الاستضافة", "خدمات البريد الإلكتروني", "التحليلات"],
    color: "purple",
  },
  {
    id: "4",
    icon: "Palette",
    title: "UI/UX Design",
    titleAr: "تصميم واجهة المستخدم",
    description: "Beautiful and intuitive user interfaces with focus on user experience.",
    descriptionAr: "واجهات مستخدم جميلة وبديهية مع التركيز على تجربة المستخدم.",
    features: ["User Research", "Wireframing", "Prototyping", "Usability Testing"],
    featuresAr: ["أبحاث المستخدم", "التخطيط الهيكلي", "النماذج الأولية", "اختبار قابلية الاستخدام"],
    color: "pink",
  },
  {
    id: "5",
    icon: "Video",
    title: "Video Editing",
    titleAr: "تحرير الفيديو",
    description: "Professional video editing services for marketing, social media, and presentations.",
    descriptionAr: "خدمات تحرير فيديو احترافية للتسويق ووسائل التواصل الاجتماعي والعروض التقديمية.",
    features: ["Motion Graphics", "Color Grading", "Sound Design", "Visual Effects"],
    featuresAr: ["رسومات متحركة", "تدرج الألوان", "تصميم الصوت", "مؤثرات بصرية"],
    color: "orange",
  },
  {
    id: "6",
    icon: "TrendingUp",
    title: "Digital Marketing",
    titleAr: "التسويق الرقمي",
    description: "Strategic marketing campaigns to grow your audience and increase conversions.",
    descriptionAr: "حملات تسويقية استراتيجية لتنمية جمهورك وزيادة التحويلات.",
    features: ["SEO", "Social Media", "Content Strategy", "Analytics & Reporting"],
    featuresAr: ["تحسين محركات البحث", "وسائل التواصل الاجتماعي", "استراتيجية المحتوى", "التحليلات والتقارير"],
    color: "cyan",
  },
];