import { TeamMember, Project, Service } from './types';
import AchrafImage from "/src/assets/teams/Achraf.JPG";



export const teamMembers: TeamMember[] = [
  {
    id: "1",
    name: "Larbi Mohammed Achraf",
    nameAr: "العربي محمد أشرف" ,
    role: "Full-Stack Web Developer",
    roleAr: "مطور ويب متكامل",
    bio: "Full-stack developer with 3+ years of experience specializing in React and Node.js et pyhthon and django",
    bioAr: "مطور متكامل مع أكثر من 3 سنوات من الخبرة متخصص في React و Node.js و pyhthon و django.",
    image: AchrafImage,
    github: "https://github.com/AchrafLarbi",
    instagram: "https://www.instagram.com/mohamedachraf123/",
    linkedin: "https://www.linkedin.com/in/larbi-achraf-01902a283/",
    email: "larbiachraf03@gmail.com",
  },
  {
    id: "2",
    name: "Ahmed Hassan",
    nameAr: "أحمد حسن",
    role: "UI/UX Designer",
    roleAr: "مصمم واجهة المستخدم",
    bio: "Creative designer with a passion for creating intuitive and beautiful user experiences.",
    bioAr: "مصمم مبدع مع شغف لإنشاء تجارب مستخدم بديهية وجميلة.",
    image: "/placeholder.svg?height=400&width=400",
    github: "https://github.com",
    instagram: "https://instagram.com",
    linkedin: "https://linkedin.com",
    email: "ahmed@example.com",
  },
  {
    id: "3",
    name: "Layla Karim",
    nameAr: "ليلى كريم",
    role: "Mobile Developer",
    roleAr: "مطور تطبيقات جوال",
    bio: "Specialized in cross-platform mobile development with React Native and Flutter.",
    bioAr: "متخصصة في تطوير تطبيقات الجوال متعددة المنصات باستخدام React Native و Flutter.",
    image: "/placeholder.svg?height=400&width=400",
    github: "https://github.com",
    instagram: "https://instagram.com",
    linkedin: "https://linkedin.com",
    email: "layla@example.com",
  },
  {
    id: "4",
    name: "Michael Chen",
    nameAr: "مايكل تشن",
    role: "Backend Engineer",
    roleAr: "مهندس الخلفية",
    bio: "Expert in scalable architecture, cloud infrastructure, and database optimization.",
    bioAr: "خبير في الهندسة المعمارية القابلة للتوسع، والبنية التحتية السحابية، وتحسين قواعد البيانات.",
    image: "/placeholder.svg?height=400&width=400",
    github: "https://github.com",
    instagram: "https://instagram.com",
    linkedin: "https://linkedin.com",
    email: "michael@example.com",
  },
];

export const projects: Project[] = [
  {
    id: 1,
    title: "E-commerce Platform",
    titleAr: "منصة التجارة الإلكترونية",
    description: "A full-featured e-commerce platform with product management, cart, and payment integration.",
    descriptionAr: "منصة تجارة إلكترونية متكاملة مع إدارة المنتجات، سلة التسوق، ودمج المدفوعات.",
    image: "/placeholder.svg?height=600&width=800",
    category: "Web",
    technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    link: "#",
    github: "https://github.com",
    date: "2023",
  },
  {
    id: 2,
    title: "Health & Fitness App",
    titleAr: "تطبيق الصحة واللياقة",
    description:
      "Mobile application for tracking workouts, nutrition, and health metrics with personalized recommendations.",
    descriptionAr: "تطبيق جوال لتتبع التمارين والتغذية ومقاييس الصحة مع توصيات مخصصة.",
    image: "/placeholder.svg?height=600&width=800",
    category: "Mobile",
    technologies: ["React Native", "Firebase", "Redux", "HealthKit"],
    link: "#",
    date: "2023",
    github: "https://github.com",
  },
  {
    id: 3,
    title: "Corporate Identity",
    titleAr: "هوية الشركة",
    description: "Complete branding package including logo design, color palette, typography, and brand guidelines.",
    descriptionAr: "حزمة علامة تجارية كاملة تشمل تصميم الشعار، لوحة الألوان، الطباعة، وإرشادات العلامة التجارية.",
    image: "/placeholder.svg?height=600&width=800",
    category: "Branding",
    technologies: ["Illustrator", "Photoshop", "InDesign"],
    link: "#",
    date: "2022",
    github: "https://github.com",
  },
  {
    id: 4,
    title: "Real Estate Portal",
    titleAr: "بوابة العقارات",
    description: "Property listing platform with advanced search, virtual tours, and agent management system.",
    descriptionAr: "منصة قوائم العقارات مع بحث متقدم، جولات افتراضية، ونظام إدارة الوكلاء.",
    image: "/placeholder.svg?height=600&width=800",
    category: "Web",
    technologies: ["Next.js", "Prisma", "PostgreSQL", "Google Maps API"],
    link: "#",
    github: "https://github.com",
    date: "2023",
  },
  {
    id: 5,
    title: "Financial Dashboard",
    titleAr: "لوحة التحكم المالية",
    description: "Interactive dashboard for financial analytics with real-time data visualization and reporting.",
    descriptionAr: "لوحة تحكم تفاعلية للتحليلات المالية مع تصور البيانات في الوقت الفعلي وإعداد التقارير.",
    image: "/placeholder.svg?height=600&width=800",
    category: "UI/UX",
    technologies: ["Figma", "Adobe XD", "Sketch"],
    link: "#",
    date: "2022",
    github: "https://github.com",
  },
  {
    id: 6,
    title: "Delivery Tracking App",
    titleAr: "تطبيق تتبع التوصيل",
    description: "Mobile application for real-time package tracking with driver management and customer notifications.",
    descriptionAr: "تطبيق جوال لتتبع الطرود في الوقت الفعلي مع إدارة السائقين وإشعارات العملاء.",
    image: "/placeholder.svg?height=600&width=800",
    category: "Mobile",
    technologies: ["Flutter", "Firebase", "Google Maps", "Push Notifications"],
    link: "#",
    github: "https://github.com",
    date: "2022",
  },
  {
    id: 7,
    title: "Educational Platform",
    titleAr: "منصة تعليمية",
    description: "Online learning platform with course management, video streaming, and interactive assessments.",
    descriptionAr: "منصة تعلم عبر الإنترنت مع إدارة الدورات، بث الفيديو، والتقييمات التفاعلية.",
    image: "/placeholder.svg?height=600&width=800",
    category: "Web",
    technologies: ["Vue.js", "Laravel", "MySQL", "WebRTC"],
    link: "#",
    date: "2021",
    github: "https://github.com",
  },
  {
    id: 8,
    title: "Restaurant Management",
    titleAr: "إدارة المطاعم",
    description:
      "Comprehensive system for restaurant operations including ordering, kitchen management, and analytics.",
    descriptionAr: "نظام شامل لعمليات المطاعم بما في ذلك الطلبات، إدارة المطبخ، والتحليلات.",
    image: "/placeholder.svg?height=600&width=800",
    category: "Web",
    technologies: ["React", "Express", "Socket.io", "PostgreSQL"],
    link: "#",
    github: "https://github.com",
    date: "2021",
  },
];

export const services: Service[] = [
  {
    id: "1",
    icon: "Code2",
    title: "Web Development",
    titleAr: "تطوير الويب",
    description: "Custom websites and web applications built with the latest technologies.",
    descriptionAr: "مواقع ويب وتطبيقات ويب مخصصة مبنية بأحدث التقنيات.",
    features: ["Responsive Design", "SEO Optimization", "Performance Tuning", "API Integration"],
    featuresAr: ["تصميم متجاوب", "تحسين محركات البحث", "ضبط الأداء", "تكامل API"],
    color: "blue",
  },
  {
    id: "2",
    icon: "Smartphone",
    title: "Mobile Development",
    titleAr: "تطوير تطبيقات الجوال",
    description: "Native and cross-platform mobile applications for iOS and Android.",
    descriptionAr: "تطبيقات جوال أصلية ومتعددة المنصات لنظامي iOS و Android.",
    features: ["Native Apps", "Cross-Platform", "Push Notifications", "Offline Support"],
    featuresAr: ["تطبيقات أصلية", "متعدد المنصات", "إشعارات فورية", "دعم وضع عدم الاتصال"],
    color: "green",
  },
  {
    id: "3",
    icon: "Globe",
    title: "Digital Presence",
    titleAr: "التواجد الرقمي",
    description: "Establish and grow your online presence with comprehensive digital solutions.",
    descriptionAr: "تأسيس وتنمية تواجدك عبر الإنترنت مع حلول رقمية شاملة.",
    features: ["Domain Setup", "Hosting Solutions", "Email Services", "Analytics"],
    featuresAr: ["إعداد النطاق", "حلول الاستضافة", "خدمات البريد الإلكتروني", "التحليلات"],
    color: "purple",
  },
  {
    id: "4",
    icon: "Palette",
    title: "UI/UX Design",
    titleAr: "تصميم واجهة المستخدم",
    description: "Beautiful and intuitive user interfaces with focus on user experience.",
    descriptionAr: "واجهات مستخدم جميلة وبديهية مع التركيز على تجربة المستخدم.",
    features: ["User Research", "Wireframing", "Prototyping", "Usability Testing"],
    featuresAr: ["أبحاث المستخدم", "التخطيط الهيكلي", "النماذج الأولية", "اختبار قابلية الاستخدام"],
    color: "pink",
  },
  {
    id: "5",
    icon: "Video",
    title: "Video Editing",
    titleAr: "تحرير الفيديو",
    description: "Professional video editing services for marketing, social media, and presentations.",
    descriptionAr: "خدمات تحرير فيديو احترافية للتسويق ووسائل التواصل الاجتماعي والعروض التقديمية.",
    features: ["Motion Graphics", "Color Grading", "Sound Design", "Visual Effects"],
    featuresAr: ["رسومات متحركة", "تدرج الألوان", "تصميم الصوت", "مؤثرات بصرية"],
    color: "orange",
  },
  {
    id: "6",
    icon: "TrendingUp",
    title: "Digital Marketing",
    titleAr: "التسويق الرقمي",
    description: "Strategic marketing campaigns to grow your audience and increase conversions.",
    descriptionAr: "حملات تسويقية استراتيجية لتنمية جمهورك وزيادة التحويلات.",
    features: ["SEO", "Social Media", "Content Strategy", "Analytics & Reporting"],
    featuresAr: ["تحسين محركات البحث", "وسائل التواصل الاجتماعي", "استراتيجية المحتوى", "التحليلات والتقارير"],
    color: "cyan",
  },
];